### PR TITLE
Myb 366 show bus stops

### PR DESCRIPTION
**Pull request by safink**
This PR resolves ticket MYB-366 that requires showing intermediate bus stops and showing them whenever the zoom changes.

intermediatebusstops

### CODE REVIEW

**Review by lisandro — APPROVED** [review]
LGTM

**Comment by marcosjvivar** [comment]
Changes are OK and ready to be merged! 🚀 and :shipit:

**Review by marcosjvivar — APPROVED** [review]
Great implementation!

**Comment by ignaciodevspark** [comment]
Looks nice, Please merge!

**Pull request merged**
