### PR TITLE
MYB-307: Networking rechability

### PR DESCRIPTION
**Pull request by ignaciodevspark**
This would implement the issue https://devspark-com.atlassian.net/browse/MYB-307 creating a class that allows other components of the app to check on the reachability.

### CODE REVIEW

**Comment by lisandro** [comment]
Hi @ignaciodevspark , approach appears to be straightforward effective but, with this class, how do I discriminate whether or not connectivity from WiFi or the cellular network? I could not test yet

**Comment by ignaciodevspark** [comment]
@lisandro I missread the issue and assumed that 3G/Wifi discrimination was not important, when it actually was. I will adapt the class in this respect.

**Comment by safink** [comment]
I guess that another good approach could be to use/implement/get ideas from this framework: https://github.com/ashleymills/Reachability.swift

**Comment by lisandro** [comment]
@ignaciodevspark changes are working as expected 👍  , just few comments. 
- Content of view with instructions is a bit not aligned. Screenshot attached
- When you go to settings and come back to app, then user continues no having connection but can use app. Honestly I think of we should tackling using a delegate's method or notification to check continuously. What is your opinion? 

**Note**: Rebase with sprint-15 to be synced and resolve conflicts.

[](https://postimg.org/image/xuta4h035/)

**Comment by ignaciodevspark** [comment]
@lisandro I believe that we should:
- Hide the map, and put some kind of a view saying "Esta aplicación necesita estar conectada a internet. Re-Intentar". Cuando el usuario apreta el botón de re-intentar, la app chequea nuevamente la conectividad y si está online volvemos a mostrar el mapa, en el caso de que no haya conectividad, de nuevo el cartel. But we must take out the map in case the user is not able to interact with the app, it would look confusing to the user.

**Comment by ignaciodevspark** [comment]
@lisandro  I've added the features we discussed, namely:
- Centered the AlertView items
- Added the "No Connection" View
- Added the "Retry" functionality too

simulator screen shot nov 8 2016 4 48 10 pm
simulator screen shot nov 8 2016 4 48 08 pm

**Comment by safink** [comment]
- The first thing I notice is that the PR was built to be merged to sprint-15 rather than sprint-16 so the base branch should be modified.
- Secondly, the alert that notifies the user that there is no-WiFi enabled displays a location icon for the step of enabling wifi instead of a Wifi icon. I believe that the xib was reused but it needs to use another asset for this step.
- Thirdly, related to the above topic, I guess that we should tell the user to either enable Wifi or else enable "Cellular data". For instance, "Habilitar Wifi / Plan de datos" could work although it's a minor detail.
- I'm not sure if hiding the map is a good idea. I guess it's better to show above the map a black semitransparent overlay view with a centered uibutton (with the icon you proposed) and a descriptive label below the button stating: "Conexión no disponible". When tapping on the button the reachability should check if there were changes in the connectivity and remove/hide the layer.

I believe that the user with this overlay realizes that there is a map below and that in order to use the app has to activate the connectivity services.

**Comment by safink** [comment]
1) I've tested the code and I'm writing a few observations,

img_0576

---

2) Until we have another design the expected scenario would be the following (@lisandro correct me if I'm wrong):

expectedscenario

In this scenario, the overlay view draws on top of the map and the search bar not allowing the user to do a search but also visually notifying that there's no connection at the moment.

**Comment by ignaciodevspark** [comment]
This looks the following way

simulator screen shot nov 15 2016 1 18 45 pm
simulator screen shot nov 15 2016 1 18 42 pm

**Pull request closed without merging**
